# Generated by Django 4.1.7 on 2023-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('release_date', models.DateField(auto_now=True)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['title'],
            },
        ),
    ]
