# Generated by Django 4.1.7 on 2023-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
